---
- name: Install ELRepo
  hosts: all

  tasks:
         - name: Enable EPEL Repo on CentOS 8
           yum:
                 name: epel-release
                 state: latest
           when: ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution_major_version'] == '8'

         - name: Enable EPEL Repo for Centos 7
           yum:
                name: epel-release
                state: latest
           when: ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution_major_version'] == '7'

         - name: Install ELRepo .RPM (CentOS 7)
           yum:
                name: http://elrepo.reloumirrors.net/elrepo/el7/x86_64/RPMS/elrepo-release-7.0-5.el7.elrepo.noarch.rpm
                state: present
           when: ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution_major_version'] == '7'

         - name: Install ELRepo .RPM (CentOS 8)
           yum:
                name: http://elrepo.reloumirrors.net/elrepo/el8/x86_64/RPMS/elrepo-release-8.2-1.el8.elrepo.noarch.rpm
                state: present
           when: ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution_major_version'] == '8'
