---
- hosts: lanhosts
  tasks:
         - name: Install Packages via yum
           yum:
                 name: "{{ packages }}"
                 state: present
                 register: yumoutput
           vars:
                 packages:
                         - htop
                         - atop
                         - iftop
                         - nmon
                         - sysstat
                         - iotop
                         - nicstat
                         - vnstat
                         - nmap
                         - bind-utils
                         - wget
                         - yum-utils
         - debug:
                  msg: "{{ yumoutput.results | map(attribute='name') | list }}"
