---
- name: Check for updates (yum)
  hosts: all

  tasks:
        - name: Check for updates (yum)
          yum: list=updates update_cache=true
          register: yumoutput
        - debug:
                msg: "{{ yumoutput.results | map(attribute='name') | list }}"
