---
- hosts: all
  tasks:
         - name: Install Packages via yum
           yum:
                 name: "{{ packages }}"
                 state: present
                 register: yumoutput
           vars:
                 packages:
                         - nmap
                         - bind-utils
                         - wget
                         - samba-client
                         - cifs-utils
                         - git
                         - yum-utils
                         - kernel-headers
                         - kernel-devel
                         - lsof
                         - mailx
                         - sendmail
                         - "@Development Tools"
                         - "@Additional Development"
         - debug:
                  msg: "{{ yumoutput.results | map(attribute='name') | list }}"
